version: '3.8'
services:
  networktoolbox:
    container_name: networktoolbox
    image: lissy93/networking-toolbox:latest
    restart: always
    environment:
      - TZ=Europe/Paris
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.networktoolbox.entrypoints=http
      - traefik.http.routers.networktoolbox.rule=Host(`networktoolbox.mondomaine.fr`)
      - traefik.http.middlewares.networktoolbox-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.networktoolbox.middlewares=SecHeader@file
      - traefik.http.routers.networktoolbox.middlewares=networktoolbox-https-redirect
      - traefik.http.routers.networktoolbox-secure.entrypoints=https
      - traefik.http.routers.networktoolbox-secure.rule=Host(`networktoolbox.mondomaine.fr`)
      - traefik.http.routers.networktoolbox.middlewares=SecHeader@file
      - traefik.http.routers.networktoolbox-secure.tls=true
      - traefik.http.routers.networktoolbox-secure.tls.options=hardening@file
      - traefik.http.routers.networktoolbox-secure.tls.certresolver=http
      - traefik.http.routers.networktoolbox-secure.service=networktoolbox
      - traefik.http.services.networktoolbox.loadbalancer.server.port=3000
networks:
  proxy:
    external: true
